// Byte-identity round-trip + generator tests for src/zcfEncoder.ts.
//
// Asserts that parse(file) -> encode(parsed) reproduces the input bytes
// exactly for three real .zcf files. If this passes, the TS port has
// the same byte-level behaviour as the Python reference encoder.
//
// Also verifies that generateZcf(spec, template):
//   - produces a file that re-parses cleanly,
//   - whose config_name + module + circuit list match the spec,
//   - and that does NOT match the template byte-for-byte (i.e. mutation
//     actually happened).

import fs from 'node:fs'
import path from 'node:path'
import {
  parseZcfFull,
  encodeZcf,
  generateZcf,
  crc8,
  crc32Lo20
} from '../dist/zcfEncoder.js'

const here = path.dirname(new URL(import.meta.url).pathname)
const fixturesDir = path.join(here, 'fixtures')

function assertEqualBytes (actual, expected, label) {
  if (actual.length !== expected.length) {
    throw new Error(`${label}: length mismatch ${actual.length} vs ${expected.length}`)
  }
  for (let i = 0; i < actual.length; i++) {
    if (actual[i] !== expected[i]) {
      const ctx = (off) => Array.from(actual.slice(Math.max(0, off - 4), off + 4)).map(b => b.toString(16).padStart(2, '0')).join(' ')
      throw new Error(`${label}: byte ${i} differs (got 0x${actual[i].toString(16)}, want 0x${expected[i].toString(16)}); context actual=[${ctx(i)}] expected=[${Array.from(expected.slice(Math.max(0, i - 4), i + 4)).map(b => b.toString(16).padStart(2, '0')).join(' ')}]`)
    }
  }
}

// CompassRose.zcf (6384 bytes) is the largest real .zcf we round-trip
// against. It is a customer config, so it isn't bundled with the plugin;
// drop a copy into test/fixtures/ to include it in the round-trip set.
const samples = ['Test.zcf', 'config-6.zcf', 'CompassRose.zcf']

for (const name of samples) {
  const filePath = path.join(fixturesDir, name)
  if (!fs.existsSync(filePath)) {
    console.log(`round-trip ${name}: SKIPPED (fixture not present)`)
    continue
  }
  const data = fs.readFileSync(filePath)
  const parsed = parseZcfFull(data)
  const out = encodeZcf(parsed)
  assertEqualBytes(out, data, `round-trip ${name}`)
  console.log(`round-trip ${name} (${data.length} bytes): OK`)
}

// CRC sanity: matches the Python reference (zcf_header.crc8 / crc32_lo20)
// for the same input.
const known = Buffer.from('Hello, world!', 'ascii')
const c8 = crc8(known)
if (c8 !== 0xbc) throw new Error(`crc8('Hello, world!') = 0x${c8.toString(16)}, want 0xbc`)
const c32 = crc32Lo20(known)
if (c32 !== 0x6c6e6) {
  throw new Error(`crc32Lo20('Hello, world!') = 0x${c32.toString(16)}, want 0x6c6e6`)
}
console.log('CRC sanity: OK')

// Generator: synthesise from Test.zcf as template.
const template = fs.readFileSync(path.join(here, '..', 'templates', 'template.zcf'))
const spec = {
  configName: 'SignalK Bank 0',
  module: { dipswitch: 0x18, name: 'SignalK Switch Bank' },
  circuits: [
    { name: 'Anchor Light', circuitId: 13 },
    { name: 'Cabin Light', circuitId: 14 },
    { name: 'Spreader Light', circuitId: 15 }
  ]
}
const generated = generateZcf(spec, template)

if (generated.equals(template)) throw new Error('generated bytes equal template — mutation did not happen')

const reparsed = parseZcfFull(generated)
if (reparsed.body.configName.name !== spec.configName) {
  throw new Error(`generated config_name = ${reparsed.body.configName.name}, want ${spec.configName}`)
}
if (reparsed.body.modules.records.length !== 1) {
  throw new Error(`generated has ${reparsed.body.modules.records.length} modules, want 1`)
}
const m = reparsed.body.modules.records[0]
if (m.dipswitch !== spec.module.dipswitch) throw new Error(`module dipswitch = 0x${m.dipswitch.toString(16)}, want 0x${spec.module.dipswitch.toString(16)}`)
if (m.name !== spec.module.name) throw new Error(`module name = ${m.name}, want ${spec.module.name}`)
if (reparsed.body.circuits.records.length !== spec.circuits.length) {
  throw new Error(`generated has ${reparsed.body.circuits.records.length} circuits, want ${spec.circuits.length}`)
}
for (let i = 0; i < spec.circuits.length; i++) {
  if (reparsed.body.circuits.records[i].name !== spec.circuits[i].name) {
    throw new Error(`circuit ${i} name = ${reparsed.body.circuits.records[i].name}, want ${spec.circuits[i].name}`)
  }
  if (reparsed.body.circuitIds.records[i].circuitId !== spec.circuits[i].circuitId) {
    throw new Error(`circuit ${i} id = ${reparsed.body.circuitIds.records[i].circuitId}, want ${spec.circuits[i].circuitId}`)
  }
  if (reparsed.body.circuitIds.records[i].name !== spec.circuits[i].name) {
    throw new Error(`circuit_id ${i} name = ${reparsed.body.circuitIds.records[i].name}, want ${spec.circuits[i].name}`)
  }
}

// Verify the generated file's CRCs by re-encoding the re-parsed structure.
const reencoded = encodeZcf(reparsed)
assertEqualBytes(reencoded, generated, 'generated re-round-trip')
console.log(`generator: produced ${generated.length}-byte .zcf with ${spec.circuits.length} circuits, re-parses cleanly, re-encodes byte-identical`)

console.log('\nzcf-encoder test: PASS')
