// Byte-identity round-trip + generator tests for src/zcfEncoder.ts.
//
// Asserts that parse(file) -> encode(parsed) reproduces the input bytes
// exactly for three real .zcf files. If this passes, the TS port has
// the same byte-level behaviour as the Python reference encoder.
//
// Also verifies that generateZcf(spec, template):
//   - produces a file that re-parses cleanly,
//   - whose config_name + module + circuit list match the spec,
//   - and that does NOT match the template byte-for-byte (i.e. mutation
//     actually happened).

import fs from 'node:fs'
import path from 'node:path'
import {
  parseZcfFull,
  encodeZcf,
  generateZcf,
  crc8,
  crc32Lo20,
  SUB_CATEGORY_BIT
} from '../dist/zcfEncoder.js'
import { parseZcf as heuristicParseZcf } from '../dist/zcfParser.js'

const here = path.dirname(new URL(import.meta.url).pathname)
const fixturesDir = path.join(here, 'fixtures')

function assertEqualBytes (actual, expected, label) {
  if (actual.length !== expected.length) {
    throw new Error(`${label}: length mismatch ${actual.length} vs ${expected.length}`)
  }
  for (let i = 0; i < actual.length; i++) {
    if (actual[i] !== expected[i]) {
      const ctx = (off) => Array.from(actual.slice(Math.max(0, off - 4), off + 4)).map(b => b.toString(16).padStart(2, '0')).join(' ')
      throw new Error(`${label}: byte ${i} differs (got 0x${actual[i].toString(16)}, want 0x${expected[i].toString(16)}); context actual=[${ctx(i)}] expected=[${Array.from(expected.slice(Math.max(0, i - 4), i + 4)).map(b => b.toString(16).padStart(2, '0')).join(' ')}]`)
    }
  }
}

// CompassRose.zcf (6384 bytes) is the largest real .zcf we round-trip
// against. It is a customer config, so it isn't bundled with the plugin;
// drop a copy into test/fixtures/ to include it in the round-trip set.
const samples = ['Test.zcf', 'config-6.zcf', 'CompassRose.zcf']

for (const name of samples) {
  const filePath = path.join(fixturesDir, name)
  if (!fs.existsSync(filePath)) {
    console.log(`round-trip ${name}: SKIPPED (fixture not present)`)
    continue
  }
  const data = fs.readFileSync(filePath)
  const parsed = parseZcfFull(data)
  const out = encodeZcf(parsed)
  assertEqualBytes(out, data, `round-trip ${name}`)
  console.log(`round-trip ${name} (${data.length} bytes): OK`)
}

// CRC sanity: matches the Python reference (zcf_header.crc8 / crc32_lo20)
// for the same input.
const known = Buffer.from('Hello, world!', 'ascii')
const c8 = crc8(known)
if (c8 !== 0xbc) throw new Error(`crc8('Hello, world!') = 0x${c8.toString(16)}, want 0xbc`)
const c32 = crc32Lo20(known)
if (c32 !== 0x6c6e6) {
  throw new Error(`crc32Lo20('Hello, world!') = 0x${c32.toString(16)}, want 0x6c6e6`)
}
console.log('CRC sanity: OK')

// Generator: synthesise from Test.zcf as template.
const template = fs.readFileSync(path.join(here, '..', 'templates', 'template.zcf'))
const spec = {
  configName: 'SignalK Bank 0',
  module: { dipswitch: 0x18, name: 'SignalK Switch Bank' },
  circuits: [
    { name: 'Anchor Light', circuitId: 13 },
    { name: 'Cabin Light', circuitId: 14 },
    { name: 'Spreader Light', circuitId: 15 }
  ]
}
const generated = generateZcf(spec, template)

if (generated.equals(template)) throw new Error('generated bytes equal template — mutation did not happen')

const reparsed = parseZcfFull(generated)
if (reparsed.body.configName.name !== spec.configName) {
  throw new Error(`generated config_name = ${reparsed.body.configName.name}, want ${spec.configName}`)
}
// 2 modules expected: our emulated Output Interface + the template's
// Display Interface (m1=0x10) which we now preserve so the
// Configuration Tool's "Display Interface" tree node is populated and
// the per-circuit "All Display Interfaces" Circuit Control binds.
if (reparsed.body.modules.records.length !== 2) {
  throw new Error(`generated has ${reparsed.body.modules.records.length} modules, want 2`)
}
const m = reparsed.body.modules.records[0]
if (m.dipswitch !== spec.module.dipswitch) throw new Error(`module dipswitch = 0x${m.dipswitch.toString(16)}, want 0x${spec.module.dipswitch.toString(16)}`)
if (m.name !== spec.module.name) throw new Error(`module name = ${m.name}, want ${spec.module.name}`)
// Generator pads to the module type's output count -- m1=0x0f is 6
// outputs, so a 3-circuit spec generates 6 circuits (3 user + 3 padded
// "Spare DC" entries to suppress the "Paralleled with DC1" placeholders
// the Configuration Tool synthesises for unused outputs).
if (reparsed.body.circuits.records.length < spec.circuits.length) {
  throw new Error(`generated has ${reparsed.body.circuits.records.length} circuits, want >= ${spec.circuits.length}`)
}
for (let i = 0; i < spec.circuits.length; i++) {
  if (reparsed.body.circuits.records[i].name !== spec.circuits[i].name) {
    throw new Error(`circuit ${i} name = ${reparsed.body.circuits.records[i].name}, want ${spec.circuits[i].name}`)
  }
  if (reparsed.body.circuitIds.records[i].circuitId !== spec.circuits[i].circuitId) {
    throw new Error(`circuit ${i} id = ${reparsed.body.circuitIds.records[i].circuitId}, want ${spec.circuits[i].circuitId}`)
  }
  if (reparsed.body.circuitIds.records[i].name !== spec.circuits[i].name) {
    throw new Error(`circuit_id ${i} name = ${reparsed.body.circuitIds.records[i].name}, want ${spec.circuits[i].name}`)
  }
}

// Verify the generated file's CRCs by re-encoding the re-parsed structure.
const reencoded = encodeZcf(reparsed)
assertEqualBytes(reencoded, generated, 'generated re-round-trip')
console.log(`generator: produced ${generated.length}-byte .zcf with ${spec.circuits.length} circuits, re-parses cleanly, re-encodes byte-identical`)

// Critical regression: every output.channelAddress and every
// displayRef.displayAddress (and circuit_id.channelAddress) must be
// dipswitch-namespaced (high byte == module dipswitch). If this drifts,
// the CZone Configuration Tool crashes in GetChannelString.
const dip = spec.module.dipswitch & 0xff
for (const ckt of reparsed.body.circuits.records) {
  for (const o of ckt.outputs) {
    // channel_address == 0x0000 is the "All Display Interfaces" wildcard
    // Circuit Control entry; it is not dipswitch-namespaced (its dip
    // byte is intentionally 0).
    if (o.channelAddress === 0) continue
    if (((o.channelAddress >> 8) & 0xff) !== dip) {
      throw new Error(`output.channelAddress 0x${o.channelAddress.toString(16)} not under dipswitch 0x${dip.toString(16)}`)
    }
  }
  for (const d of ckt.displayRefs) {
    if (((d.displayAddress >> 8) & 0xff) !== dip) {
      throw new Error(`dref.displayAddress 0x${d.displayAddress.toString(16)} not under dipswitch 0x${dip.toString(16)}`)
    }
  }
}
for (const cid of reparsed.body.circuitIds.records) {
  if (((cid.channelAddress >> 8) & 0xff) !== dip) {
    throw new Error(`circuit_id.channelAddress 0x${cid.channelAddress.toString(16)} not under dipswitch 0x${dip.toString(16)}`)
  }
}
console.log(`channel-address dipswitch namespacing (high byte == 0x${dip.toString(16)}): OK`)

// Heuristic parser sanity: drive the generated bytes through the SAME
// scanner the runtime uses on inbound PGN 130816 reassembly. The parser
// scans for length-prefixed strings appearing >= 2x; some labels (the
// module name, the labelled-entity name) can show up twice for unrelated
// reasons and inflate the count, so we only assert that every spec
// circuit is present, not that the count matches exactly.
const heuristic = heuristicParseZcf(generated)
const heurNames = new Set(heuristic.circuits.map(c => c.name))
for (const c of spec.circuits) {
  if (!heurNames.has(c.name)) {
    throw new Error(`heuristic parser missing circuit name ${JSON.stringify(c.name)}; saw ${JSON.stringify([...heurNames])}`)
  }
}
const heurIdsForSpec = spec.circuits.map(c => {
  const found = heuristic.circuits.find(h => h.name === c.name)
  return found ? found.circuitId : -1
})
for (let i = 0; i < spec.circuits.length; i++) {
  if (heurIdsForSpec[i] !== spec.circuits[i].circuitId) {
    throw new Error(`heuristic parser id for ${spec.circuits[i].name} = ${heurIdsForSpec[i]}, want ${spec.circuits[i].circuitId}`)
  }
}
console.log(`heuristic parser sees all ${spec.circuits.length} spec circuits with correct ids (total parsed: ${heuristic.circuits.length}): OK`)

// Larger spec -- 8 switches, names with characters that exercise the
// length-prefix scanner (numbers, spaces).
const bigSpec = {
  configName: 'My Boat Configuration',
  module: { dipswitch: 0x18, name: 'Helm Switch Bank' },
  circuits: [
    { name: 'Anchor Light', circuitId: 13 },
    { name: 'Cabin Light 1', circuitId: 14 },
    { name: 'Cabin Light 2', circuitId: 15 },
    { name: 'Spreader Light', circuitId: 16 },
    { name: 'Salon Lights', circuitId: 17 },
    { name: 'Galley Lights', circuitId: 18 },
    { name: 'Bilge Pump', circuitId: 19 },
    { name: 'Nav Lights', circuitId: 20 }
  ]
}
const bigGen = generateZcf(bigSpec, template)
const bigParsed = parseZcfFull(bigGen)  // re-parses cleanly
if (bigParsed.body.circuits.records.length !== bigSpec.circuits.length) {
  throw new Error(`big spec: parsed ${bigParsed.body.circuits.records.length} circuits, want ${bigSpec.circuits.length}`)
}
const bigHeuristic = heuristicParseZcf(bigGen)
const bigHeurNames = new Set(bigHeuristic.circuits.map(c => c.name))
for (const c of bigSpec.circuits) {
  if (!bigHeurNames.has(c.name)) {
    throw new Error(`big spec heuristic missing ${JSON.stringify(c.name)}`)
  }
}
console.log(`generator: 8-circuit spec generated ${bigGen.length} bytes, both parsers see all 8 spec circuits`)

// Sub-category: a per-circuit subCategory value lands in the
// circuits-section flags_b verbatim. Verify each spec circuit's
// flags_b matches the supplied subCategory.
const catSpec = {
  configName: 'Cat Test',
  module: { dipswitch: 0x18, name: 'Cat Module' },
  circuits: [
    { name: 'Anchor Light', circuitId: 13, subCategory: SUB_CATEGORY_BIT.NAVIGATION },
    { name: 'Cabin Lights', circuitId: 14, subCategory: SUB_CATEGORY_BIT.LIGHTING },
    { name: 'Bilge Pump',   circuitId: 15, subCategory: SUB_CATEGORY_BIT.PUMPS },
    { name: 'Fridge',       circuitId: 16, subCategory: SUB_CATEGORY_BIT.REFRIGERATION },
    { name: 'VHF',          circuitId: 17, subCategory: SUB_CATEGORY_BIT.COMMUNICATIONS },
    { name: 'LPG',          circuitId: 18, subCategory: SUB_CATEGORY_BIT.HOUSE_HABITAT },
    // No subCategory -> template's flags_b is preserved
    { name: 'Other',        circuitId: 19 }
  ]
}
const catGen = generateZcf(catSpec, template)
const catParsed = parseZcfFull(catGen)
const expectedFlagsB = [
  SUB_CATEGORY_BIT.NAVIGATION,
  SUB_CATEGORY_BIT.LIGHTING,
  SUB_CATEGORY_BIT.PUMPS,
  SUB_CATEGORY_BIT.REFRIGERATION,
  SUB_CATEGORY_BIT.COMMUNICATIONS,
  SUB_CATEGORY_BIT.HOUSE_HABITAT,
  null  // template's flags_b -- Test.zcf is 0x0002 for first circuit
]
for (let i = 0; i < catSpec.circuits.length; i++) {
  const got = catParsed.body.circuits.records[i].flagsB
  const want = expectedFlagsB[i]
  if (want === null) continue  // template-preserved; don't pin a value
  if (got !== want) {
    throw new Error(`circuit ${i} (${catSpec.circuits[i].name}) flags_b = 0x${got.toString(16)}, want 0x${want.toString(16)}`)
  }
}
console.log(`generator: per-circuit subCategory threaded into flags_b correctly: OK`)

// Bank instance: spec.bankInstance lands in labelled_entities[0].field_b.
// Verified against config-6.zcf (field_b=5 + name "SW Bank 5"). Without
// this rewrite the Configuration Tool's Switch Bank PGN config row shows
// Switch Bank Instance = 0 regardless of the user's bank.instance.
const bankSpec = {
  configName: 'Bank 16 Test',
  module: { dipswitch: 0x08, name: 'Bank 16 Module' },
  bankInstance: 16,
  circuits: [{ name: 'Switch 1', circuitId: 13 }]
}
const bankGen = generateZcf(bankSpec, template)
const bankParsed = parseZcfFull(bankGen)
const labelEntsTrailing = bankParsed.body.trailingSections[21]
if (!labelEntsTrailing || labelEntsTrailing.payload.length < 5) {
  throw new Error('labelled_entities trailing section missing or too short')
}
const fieldB = labelEntsTrailing.payload[2]
if (fieldB !== 16) {
  throw new Error(`labelled_entities[0].field_b = ${fieldB}, want 16 (the bank instance)`)
}
console.log(`generator: bankInstance landed in labelled_entities[0].field_b: OK`)

// Empty labelled-entity name hangs the plotter (czone-spec/spec/zcf-parser.md
// "Pathological-input hangs"). The generator must refuse to emit such a file.
let emptyNameRejected = false
try {
  generateZcf({ ...bankSpec, module: { ...bankSpec.module, name: '' } }, template)
} catch (err) {
  if (/empty name hangs the plotter|labelled_entities name must be at least 1 byte/i.test(err.message)) {
    emptyNameRejected = true
  } else {
    throw err
  }
}
if (!emptyNameRejected) {
  throw new Error('empty module name should have thrown; generator emitted a hang-inducing .zcf')
}
console.log(`generator: empty labelled-entity name is refused (plotter-hang guard): OK`)

// Paralleled-output suppression: with module type m1=0x0f (3 outputs),
// supplying 1 spec circuit pads to 3 generated circuits so the
// Configuration Tool doesn't show "DC{n} - Paralleled with DC1" rows.
// (Test.zcf's module is m1=0x0f, our generated test files inherit it.)
if (bankParsed.body.circuits.records.length !== 6) {
  throw new Error(`expected 6 circuits after padding (m1=0x0f -> 6 outputs), got ${bankParsed.body.circuits.records.length}`)
}
const paddingNames = bankParsed.body.circuits.records.slice(1).map(c => c.name)
if (paddingNames[0] !== 'Spare DC2' || paddingNames[4] !== 'Spare DC6') {
  throw new Error(`unexpected padding names: ${JSON.stringify(paddingNames)}`)
}
console.log(`generator: padded 1 spec circuit -> 6 generated circuits to match m1=0x0f output count: OK`)

// Display Interface + wildcard output: every generated circuit must
// have a leading outputs[0] with channelAddress = 0x0000 (the "All
// Display Interfaces" wildcard the Configuration Tool's Circuit
// Control surface keys off), AND the modules list must include both
// our Output Interface (m1=0x0f) and the template's Display Interface
// (m1=0x10) -- otherwise mister nui's side-bar binding doesn't work.
const sidebarSpec = {
  configName: 'Sidebar Test',
  module: { dipswitch: 0x18, name: 'Sidebar Module' },
  bankInstance: 0,
  circuits: [{ name: 'Lights', circuitId: 13 }]
}
const sidebarGen = generateZcf(sidebarSpec, template)
const sidebarParsed = parseZcfFull(sidebarGen)
if (sidebarParsed.body.modules.records.length < 2) {
  throw new Error(`sidebar config: expected >=2 modules (Output + Display Interface), got ${sidebarParsed.body.modules.records.length}`)
}
const hasDisplayInterface = sidebarParsed.body.modules.records.some(m => m.moduleSpecificValue === 0x10)
if (!hasDisplayInterface) {
  throw new Error(`sidebar config: no Display Interface module (m1=0x10) in generated file -- "All Display Interfaces" Circuit Control will be missing`)
}
for (const ckt of sidebarParsed.body.circuits.records) {
  // Wildcard-only outputs per circuit. Verified 2026-05-10 against
  // Scott's working Gannet-nosb_Scott_works.zcf, which has exactly one
  // output (chan=0x0000) per circuit. The earlier two-output pattern
  // (wildcard + a synthetic physical-output binding) produced channel
  // addresses outside the module's actual output range and caused
  // MFDApp to silently reject the .zcf, leaving the plotter stuck on
  // "Starting configuration claim". See src/zcfEncoder.ts comments.
  if (ckt.outputs.length !== 1 || ckt.outputs[0].channelAddress !== 0) {
    throw new Error(`circuit ${ckt.name} expected exactly one wildcard output chan=0x0000 (got outputs=${ckt.outputs.map(o => '0x' + o.channelAddress.toString(16)).join(',')})`)
  }
}
console.log(`generator: every circuit has wildcard-only output + Display Interface module preserved: OK`)

// Module type override: spec.module.typeCode rewrites the module's
// module_specific_value byte. Three of the four currently-known type
// codes are exercised here -- each one was verified by importing a
// generated file in the CZone Configuration Tool on Windows and
// reading the Modules tab tree label:
//   m1=0x0f -> "Output Interface", 6 outputs (the default, exercised
//              by every generator test above)
//   m1=0x1c -> "Control 1", 16 outputs (80-911-0122-00). A separate
//              Mastervolt product that shares COI's 16-channel
//              layout but has its own hardware identity.
//   m1=0x1f -> "Combination Output Interface", 16 outputs DC1..DC16
//              (modern hardware: 4 high-current + 12 dimmable, 150A
//              max). Parts 80-911-0119-00 (modern) / 80-911-0120-00
//              (legacy).
const control1Spec = {
  configName: 'Control 1 Test',
  module: { dipswitch: 0x10, name: 'Control 1', typeCode: 0x1c },
  bankInstance: 0,
  circuits: [{ name: 'DC1 Load', circuitId: 13 }]
}
const control1Gen = generateZcf(control1Spec, template)
const control1Parsed = parseZcfFull(control1Gen)
if (control1Parsed.body.modules.records[0].moduleSpecificValue !== 0x1c) {
  throw new Error(`Control 1 typeCode override failed: got 0x${control1Parsed.body.modules.records[0].moduleSpecificValue.toString(16)}, want 0x1c`)
}
if (control1Parsed.body.circuits.records.length !== 16) {
  throw new Error(`Control 1 1-circuit spec should pad to 16 circuits, got ${control1Parsed.body.circuits.records.length}`)
}
console.log(`generator: typeCode override 0x1c (Control 1, 16 outputs) pads to 16 circuits: OK`)

const coiSpec = {
  configName: 'COI 16-Channel Test',
  module: { dipswitch: 0x21, name: 'COI 16-CH', typeCode: 0x1f },
  bankInstance: 1,
  circuits: [{ name: 'High Current 1', circuitId: 13 }]
}
const coiGen = generateZcf(coiSpec, template)
const coiParsed = parseZcfFull(coiGen)
if (coiParsed.body.modules.records[0].moduleSpecificValue !== 0x1f) {
  throw new Error(`COI typeCode override failed: got 0x${coiParsed.body.modules.records[0].moduleSpecificValue.toString(16)}, want 0x1f`)
}
if (coiParsed.body.circuits.records.length !== 16) {
  throw new Error(`COI 1-circuit spec should pad to 16 circuits, got ${coiParsed.body.circuits.records.length}`)
}
console.log(`generator: typeCode override 0x1f (COI, 16 outputs) pads to 16 circuits: OK`)

// mfdDipswitch: when supplied, the Display Interface module's dipswitch
// in the generated .zcf should match the supplied value verbatim (instead
// of the legacy "lowest unused" fallback that picked dipswitch 1 for
// Scott's COI test, causing SV MOIN's plotter to hang in state 0
// "Starting configuration claim" because the real plotter's dipswitch
// wasn't 1). Spec ref: czone-spec/spec/czone-config-state-machine.md.
const mfdSpec = {
  configName: 'MFD Dipswitch Test',
  module: { dipswitch: 0x05, name: 'Test Module' },
  bankInstance: 0,
  mfdDipswitch: 0x42,
  circuits: [{ name: 'Switch 1', circuitId: 13 }]
}
const mfdGen = generateZcf(mfdSpec, template)
const mfdParsed = parseZcfFull(mfdGen)
const displayModule = mfdParsed.body.modules.records.find(m => m.moduleSpecificValue === 0x10)
if (!displayModule) {
  throw new Error('mfdDipswitch test: no Display Interface module in generated file')
}
if (displayModule.dipswitch !== 0x42) {
  throw new Error(`mfdDipswitch test: Display Interface dipswitch = ${displayModule.dipswitch}, want 0x42`)
}
console.log(`generator: mfdDipswitch=0x42 pinned the Display Interface module dipswitch: OK`)

// mfdDipswitch must differ from module.dipswitch.
let mfdConflictRejected = false
try {
  generateZcf({ ...mfdSpec, mfdDipswitch: 0x05 }, template)
} catch (err) {
  if (/mfdDipswitch.*must differ from module\.dipswitch/i.test(err.message)) {
    mfdConflictRejected = true
  } else {
    throw err
  }
}
if (!mfdConflictRejected) {
  throw new Error('mfdDipswitch test: passing mfdDipswitch == module.dipswitch should have thrown')
}
console.log(`generator: mfdDipswitch == module.dipswitch is refused: OK`)

// Run czone-spec/tools/zcf_validate.py against a generated .zcf if it's
// available on this machine. The validator implements every checkable rule
// in czone-spec/spec/zcf-validation.md (H1-H7 header, F1-F7 framing, D1-D8
// dipswitch consistency, O1-O2 output counts, T1 labelled-entity hang
// guard). Exit code 0 = no FAILs. Skipped (with a note) when czone-spec
// isn't checked out as a sibling of this repo.
const validatorPath = path.resolve(here, '..', '..', 'czone-spec', 'tools', 'zcf_validate.py')
if (fs.existsSync(validatorPath)) {
  const tmpZcf = path.join(here, '.tmp-validator-input.zcf')
  fs.writeFileSync(tmpZcf, coiGen)
  try {
    const { spawnSync } = await import('node:child_process')
    const r = spawnSync('python3', [validatorPath, tmpZcf, '--quiet'], { encoding: 'utf8' })
    if (r.status === null) throw new Error(`could not invoke python3: ${r.error?.message ?? r.error}`)
    if (r.status !== 0) {
      throw new Error(`zcf_validate.py reported FAIL on a freshly-generated .zcf:\n${r.stdout}\n${r.stderr}`)
    }
    console.log(`generator: czone-spec validator (zcf_validate.py) reports 0 FAIL on generated .zcf: OK`)
  } finally {
    try { fs.unlinkSync(tmpZcf) } catch (_) {}
  }
} else {
  console.log(`generator: skipped czone-spec validator check (${validatorPath} not present)`)
}

console.log('\nzcf-encoder test: PASS')
