// Byte-identity round-trip + generator tests for src/zcfEncoder.ts.
//
// Asserts that parse(file) -> encode(parsed) reproduces the input bytes
// exactly for three real .zcf files. If this passes, the TS port has
// the same byte-level behaviour as the Python reference encoder.
//
// Also verifies that generateZcf(spec, template):
//   - produces a file that re-parses cleanly,
//   - whose config_name + module + circuit list match the spec,
//   - and that does NOT match the template byte-for-byte (i.e. mutation
//     actually happened).

import fs from 'node:fs'
import path from 'node:path'
import {
  parseZcfFull,
  encodeZcf,
  generateZcf,
  crc8,
  crc32Lo20,
  SUB_CATEGORY_BIT
} from '../dist/zcfEncoder.js'
import { parseZcf as heuristicParseZcf } from '../dist/zcfParser.js'

const here = path.dirname(new URL(import.meta.url).pathname)
const fixturesDir = path.join(here, 'fixtures')

function assertEqualBytes (actual, expected, label) {
  if (actual.length !== expected.length) {
    throw new Error(`${label}: length mismatch ${actual.length} vs ${expected.length}`)
  }
  for (let i = 0; i < actual.length; i++) {
    if (actual[i] !== expected[i]) {
      const ctx = (off) => Array.from(actual.slice(Math.max(0, off - 4), off + 4)).map(b => b.toString(16).padStart(2, '0')).join(' ')
      throw new Error(`${label}: byte ${i} differs (got 0x${actual[i].toString(16)}, want 0x${expected[i].toString(16)}); context actual=[${ctx(i)}] expected=[${Array.from(expected.slice(Math.max(0, i - 4), i + 4)).map(b => b.toString(16).padStart(2, '0')).join(' ')}]`)
    }
  }
}

// CompassRose.zcf (6384 bytes) is the largest real .zcf we round-trip
// against. It is a customer config, so it isn't bundled with the plugin;
// drop a copy into test/fixtures/ to include it in the round-trip set.
const samples = ['Test.zcf', 'config-6.zcf', 'CompassRose.zcf']

for (const name of samples) {
  const filePath = path.join(fixturesDir, name)
  if (!fs.existsSync(filePath)) {
    console.log(`round-trip ${name}: SKIPPED (fixture not present)`)
    continue
  }
  const data = fs.readFileSync(filePath)
  const parsed = parseZcfFull(data)
  const out = encodeZcf(parsed)
  assertEqualBytes(out, data, `round-trip ${name}`)
  console.log(`round-trip ${name} (${data.length} bytes): OK`)
}

// CRC sanity: matches the Python reference (zcf_header.crc8 / crc32_lo20)
// for the same input.
const known = Buffer.from('Hello, world!', 'ascii')
const c8 = crc8(known)
if (c8 !== 0xbc) throw new Error(`crc8('Hello, world!') = 0x${c8.toString(16)}, want 0xbc`)
const c32 = crc32Lo20(known)
if (c32 !== 0x6c6e6) {
  throw new Error(`crc32Lo20('Hello, world!') = 0x${c32.toString(16)}, want 0x6c6e6`)
}
console.log('CRC sanity: OK')

// Generator: synthesise from Test.zcf as template.
const template = fs.readFileSync(path.join(here, '..', 'templates', 'template.zcf'))
const spec = {
  configName: 'SignalK Bank 0',
  module: { dipswitch: 0x18, name: 'SignalK Switch Bank' },
  circuits: [
    { name: 'Anchor Light', circuitId: 13 },
    { name: 'Cabin Light', circuitId: 14 },
    { name: 'Spreader Light', circuitId: 15 }
  ]
}
const generated = generateZcf(spec, template)

if (generated.equals(template)) throw new Error('generated bytes equal template — mutation did not happen')

const reparsed = parseZcfFull(generated)
if (reparsed.body.configName.name !== spec.configName) {
  throw new Error(`generated config_name = ${reparsed.body.configName.name}, want ${spec.configName}`)
}
if (reparsed.body.modules.records.length !== 1) {
  throw new Error(`generated has ${reparsed.body.modules.records.length} modules, want 1`)
}
const m = reparsed.body.modules.records[0]
if (m.dipswitch !== spec.module.dipswitch) throw new Error(`module dipswitch = 0x${m.dipswitch.toString(16)}, want 0x${spec.module.dipswitch.toString(16)}`)
if (m.name !== spec.module.name) throw new Error(`module name = ${m.name}, want ${spec.module.name}`)
if (reparsed.body.circuits.records.length !== spec.circuits.length) {
  throw new Error(`generated has ${reparsed.body.circuits.records.length} circuits, want ${spec.circuits.length}`)
}
for (let i = 0; i < spec.circuits.length; i++) {
  if (reparsed.body.circuits.records[i].name !== spec.circuits[i].name) {
    throw new Error(`circuit ${i} name = ${reparsed.body.circuits.records[i].name}, want ${spec.circuits[i].name}`)
  }
  if (reparsed.body.circuitIds.records[i].circuitId !== spec.circuits[i].circuitId) {
    throw new Error(`circuit ${i} id = ${reparsed.body.circuitIds.records[i].circuitId}, want ${spec.circuits[i].circuitId}`)
  }
  if (reparsed.body.circuitIds.records[i].name !== spec.circuits[i].name) {
    throw new Error(`circuit_id ${i} name = ${reparsed.body.circuitIds.records[i].name}, want ${spec.circuits[i].name}`)
  }
}

// Verify the generated file's CRCs by re-encoding the re-parsed structure.
const reencoded = encodeZcf(reparsed)
assertEqualBytes(reencoded, generated, 'generated re-round-trip')
console.log(`generator: produced ${generated.length}-byte .zcf with ${spec.circuits.length} circuits, re-parses cleanly, re-encodes byte-identical`)

// Critical regression: every output.channelAddress and every
// displayRef.displayAddress (and circuit_id.channelAddress) must be
// dipswitch-namespaced (high byte == module dipswitch). If this drifts,
// the CZone Configuration Tool crashes in GetChannelString.
const dip = spec.module.dipswitch & 0xff
for (const ckt of reparsed.body.circuits.records) {
  for (const o of ckt.outputs) {
    if (((o.channelAddress >> 8) & 0xff) !== dip) {
      throw new Error(`output.channelAddress 0x${o.channelAddress.toString(16)} not under dipswitch 0x${dip.toString(16)}`)
    }
  }
  for (const d of ckt.displayRefs) {
    if (((d.displayAddress >> 8) & 0xff) !== dip) {
      throw new Error(`dref.displayAddress 0x${d.displayAddress.toString(16)} not under dipswitch 0x${dip.toString(16)}`)
    }
  }
}
for (const cid of reparsed.body.circuitIds.records) {
  if (((cid.channelAddress >> 8) & 0xff) !== dip) {
    throw new Error(`circuit_id.channelAddress 0x${cid.channelAddress.toString(16)} not under dipswitch 0x${dip.toString(16)}`)
  }
}
console.log(`channel-address dipswitch namespacing (high byte == 0x${dip.toString(16)}): OK`)

// Heuristic parser sanity: drive the generated bytes through the SAME
// scanner the runtime uses on inbound PGN 130816 reassembly. The parser
// scans for length-prefixed strings appearing >= 2x; some labels (the
// module name, the labelled-entity name) can show up twice for unrelated
// reasons and inflate the count, so we only assert that every spec
// circuit is present, not that the count matches exactly.
const heuristic = heuristicParseZcf(generated)
const heurNames = new Set(heuristic.circuits.map(c => c.name))
for (const c of spec.circuits) {
  if (!heurNames.has(c.name)) {
    throw new Error(`heuristic parser missing circuit name ${JSON.stringify(c.name)}; saw ${JSON.stringify([...heurNames])}`)
  }
}
const heurIdsForSpec = spec.circuits.map(c => {
  const found = heuristic.circuits.find(h => h.name === c.name)
  return found ? found.circuitId : -1
})
for (let i = 0; i < spec.circuits.length; i++) {
  if (heurIdsForSpec[i] !== spec.circuits[i].circuitId) {
    throw new Error(`heuristic parser id for ${spec.circuits[i].name} = ${heurIdsForSpec[i]}, want ${spec.circuits[i].circuitId}`)
  }
}
console.log(`heuristic parser sees all ${spec.circuits.length} spec circuits with correct ids (total parsed: ${heuristic.circuits.length}): OK`)

// Larger spec -- 8 switches, names with characters that exercise the
// length-prefix scanner (numbers, spaces).
const bigSpec = {
  configName: 'My Boat Configuration',
  module: { dipswitch: 0x18, name: 'Helm Switch Bank' },
  circuits: [
    { name: 'Anchor Light', circuitId: 13 },
    { name: 'Cabin Light 1', circuitId: 14 },
    { name: 'Cabin Light 2', circuitId: 15 },
    { name: 'Spreader Light', circuitId: 16 },
    { name: 'Salon Lights', circuitId: 17 },
    { name: 'Galley Lights', circuitId: 18 },
    { name: 'Bilge Pump', circuitId: 19 },
    { name: 'Nav Lights', circuitId: 20 }
  ]
}
const bigGen = generateZcf(bigSpec, template)
const bigParsed = parseZcfFull(bigGen)  // re-parses cleanly
if (bigParsed.body.circuits.records.length !== bigSpec.circuits.length) {
  throw new Error(`big spec: parsed ${bigParsed.body.circuits.records.length} circuits, want ${bigSpec.circuits.length}`)
}
const bigHeuristic = heuristicParseZcf(bigGen)
const bigHeurNames = new Set(bigHeuristic.circuits.map(c => c.name))
for (const c of bigSpec.circuits) {
  if (!bigHeurNames.has(c.name)) {
    throw new Error(`big spec heuristic missing ${JSON.stringify(c.name)}`)
  }
}
console.log(`generator: 8-circuit spec generated ${bigGen.length} bytes, both parsers see all 8 spec circuits`)

// Sub-category: a per-circuit subCategory value lands in the
// circuits-section flags_b verbatim. Verify each spec circuit's
// flags_b matches the supplied subCategory.
const catSpec = {
  configName: 'Cat Test',
  module: { dipswitch: 0x18, name: 'Cat Module' },
  circuits: [
    { name: 'Anchor Light', circuitId: 13, subCategory: SUB_CATEGORY_BIT.NAVIGATION },
    { name: 'Cabin Lights', circuitId: 14, subCategory: SUB_CATEGORY_BIT.LIGHTING },
    { name: 'Bilge Pump',   circuitId: 15, subCategory: SUB_CATEGORY_BIT.PUMPS },
    { name: 'Fridge',       circuitId: 16, subCategory: SUB_CATEGORY_BIT.REFRIGERATION },
    { name: 'VHF',          circuitId: 17, subCategory: SUB_CATEGORY_BIT.COMMUNICATIONS },
    { name: 'LPG',          circuitId: 18, subCategory: SUB_CATEGORY_BIT.HOUSE_HABITAT },
    // No subCategory -> template's flags_b is preserved
    { name: 'Other',        circuitId: 19 }
  ]
}
const catGen = generateZcf(catSpec, template)
const catParsed = parseZcfFull(catGen)
const expectedFlagsB = [
  SUB_CATEGORY_BIT.NAVIGATION,
  SUB_CATEGORY_BIT.LIGHTING,
  SUB_CATEGORY_BIT.PUMPS,
  SUB_CATEGORY_BIT.REFRIGERATION,
  SUB_CATEGORY_BIT.COMMUNICATIONS,
  SUB_CATEGORY_BIT.HOUSE_HABITAT,
  null  // template's flags_b -- Test.zcf is 0x0002 for first circuit
]
for (let i = 0; i < catSpec.circuits.length; i++) {
  const got = catParsed.body.circuits.records[i].flagsB
  const want = expectedFlagsB[i]
  if (want === null) continue  // template-preserved; don't pin a value
  if (got !== want) {
    throw new Error(`circuit ${i} (${catSpec.circuits[i].name}) flags_b = 0x${got.toString(16)}, want 0x${want.toString(16)}`)
  }
}
console.log(`generator: per-circuit subCategory threaded into flags_b correctly: OK`)

console.log('\nzcf-encoder test: PASS')
